version: '3.8'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: data_board
      MONGO_INTDB_ROLE: readWrite
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "8866:8866"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/data_board?authSource=admin

volumes:
  mongo_data:
